### PR TITLE
fix: package-lock is json & github handler changed

### PR DESCRIPTION
**Pull request by sherhy**

### CODE REVIEW

**Review by miraiakagawa — DISMISSED** [review]
lgtm

**Comment by miraiakagawa** [comment]
@sherhy please go ahead and merge this (Squash and merge) at your convenience.

**Comment by miraiakagawa** [comment]
@sherhy actually, there were some changes that I had not pushed... can you rebase main and resolve the conflict?

**Comment by sherhy** [comment]
@miraiakagawa looks like rebases require a review once again

**Review by miraiakagawa — APPROVED** [review]

**Pull request merged**
